version: "3"

services:
    messaging:
        build: ./zambda
        container_name: "messaging_app"
        ports:
            - 8000:8000
        volumes:
            - .:/app

    enginx:
        build: ./docker/nginx
        container_name: "enginx"
        ports:
            - 4000:8000

    redis:
        build: ./docker/redis
        container_name: "redis_database"
        ports:
            - "6379:6379"
