version: "3"

services:
    messaging:
        build: ./zambda
        container_name: "messaging_app"
        ports:
            - "40:80"
        volumes:
            - .:/app

    enginx:
        build: ./docker/nginx
        container_name: "enginx"
        ports:
            - "50:80"

    redis:
        build: ./docker/redis
        container_name: "redis_database"
        ports:
            - "6379:6379"