version: "3"

services:
    messaging:
        build: ./zambda
        container_name: "messaging_app"
        environment:
            - REDIS_HOST=redis
        ports:
            - 8000:8000
        volumes:
            - .:/app
            
    enginx:
        build: ./docker/nginx
        container_name: "enginx"
        ports:
            - 4000:8000

    redis:
        build: ./docker/redis
        container_name: "redis_database"
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data: {}

networks:
    my_network:
        name: "my_network_test"
        # ipv4_address: 172.16.238.10 