# Generated by Django 3.0.4 on 2020-03-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('from_user', models.PositiveIntegerField()),
                ('to_user', models.PositiveIntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('thread_reference', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.MessagesThread')),
            ],
        ),
    ]
