# Generated by Django 3.0.4 on 2020-07-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='reference',
            field=models.CharField(blank=True, default='e4c7677830', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message', 'message_html'], name='forum_messa_message_4e5856_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['name', 'reference'], name='forum_threa_name_fe7cb6_idx'),
        ),
    ]
