# Generated by Django 3.0.4 on 2020-03-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesthread',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
