# Generated by Django 3.0.4 on 2020-05-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_messagesthread_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesthread',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='messagesthread',
            name='to_user',
        ),
    ]
