# Generated by Django 3.0.4 on 2020-07-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200724_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='reference',
            field=models.CharField(blank=True, default='3a9279adbd', max_length=100, null=True),
        ),
    ]
