# Generated by Django 3.0.8 on 2020-07-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200724_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='reference',
            field=models.CharField(blank=True, default='aa37cd2a09', max_length=100, null=True),
        ),
    ]
