# Generated by Django 3.0.4 on 2020-05-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200531_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesthread',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
